version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "GuessingGame-API"
    environment:
      SIGNATURE: "mySignature"
    ports:
      - "8080:8080"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge