version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "GuessingGame-API"
    environment:
      SIGNATURE: "mySignature"
    ports:
      - "8080:8080"
    networks:
      - fullstack
  frontend:
    build: ./frontend
    container_name: "GuessingGame-React"
    ports: 
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge